### PR TITLE
modifications for using synthetic data

### PR DESCRIPTION
**Pull request by wbaccinelli**
I made some modifications in order to facilitate the use of the package with synthetic data:
- Added a notebook called `getting_started` where it is shown how to create synthetic data and they are used for a basic analysis pipeline implementation.
- Removed the use of the config file from the cli. It was actually not used, but the absence of the file was blocking for using all the commands.
- Modified the `basic_emg_analysis` notebook to use a default location if the config file does not exist, and to make use of both Poli5 and npy files.
- Added a file with EMG synthetic data. We can decide whether to keep this or not.

### CODE REVIEW

**Comment by drcandacemakedamoore** [comment]
@wbaccinelli the idea with the config in the cli is that if you feed no value it will default to what is in the config file for certain things e.g. parsed.input if you don't feed will default to 'data' from the config. Did it not work this way for you?

**Comment by wbaccinelli** [comment]
> @wbaccinelli the idea with the config in the cli is that if you feed no value it will default to what is in the config file for certain things e.g. parsed.input if you don't feed will default to 'data' from the config. Did it not work this way for you?

Oh, I see. We might want to make the presence of the config file not blocking anyway, especially if the user specifies the paths. Now the file presence check is mandatory, but I can maybe modify the flow a bit? What do you think?

**Comment by drcandacemakedamoore** [comment]
The best would be to leave the config default, but not have it block in the case of anything from the cli module, and that is how it is supposed to work. If you specify a file, it should be overwriting whatever is in the config. But I never tested without a config file at all.

**Comment by wbaccinelli** [comment]
I agree. But , at the moment, the `Config` [is always initialized](https://github.com/ReSurfEMG/ReSurfEMG/blob/ccc59de58883b7dec02a7db5e019c4f98e23b346/resurfemg/cli.py#L176) when running the cli. I can also check the arguments to see whether the user wanted to use the default or not, so to make the config file presence not blocking in case it is not needed.

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
@wbaccinelli 
The basic_emg_analysis notebook now has a flow that breaks for me. At first I was on the wrong branch, but now I see the changed notebook. Unfortunately, 'emg_pattern = os.path.join(root_emg_directory, '**/*{x}'.format( x = posible_extensions))' doesn't work propery when you run from the config with Poly5 files now. ALso I would change 'root_emg_directory = '..\\synth_data\\synth_emg'' to just use os.path.join, and avoid issues with Apple and other machines that might not have the same escape character/backslash patterns. i.e. 'root_emg_directory = os.path.join(.., synth_data, synth_emg)' or something like that

**Comment by wbaccinelli** [comment]
> @wbaccinelli The basic_emg_analysis notebook now has a flow that breaks for me. At first I was on the wrong branch, but now I see the changed notebook. Unfortunately, 'emg_pattern = os.path.join(root_emg_directory, '**/*{x}'.format( x = posible_extensions))' doesn't work propery when you run from the config with Poly5 files now. ALso I would change 'root_emg_directory = '..\synth_data\synth_emg'' to just use os.path.join, and avoid issues with Apple and other machines that might not have the same escape character/backslash patterns. i.e. 'root_emg_directory = os.path.join(.., synth_data, synth_emg)' or something like that

@drcandacemakedamoore I tried once more with the config file pointing to Poly5 files, but I cannot reproduce the issue. Good idea using `os.path.join`

**Review by drcandacemakedamoore — APPROVED** [review]
OK, it works now!

**Comment by drcandacemakedamoore** [comment]
Maybe just add a note that we need at least 2 leads on the .npy file, or the notebook will break. But not necessary

**Pull request merged**
