### PR TITLE
Exclude nan values from mean in gating method 2

### LINKED ISSUE #143: Nans returned by gating method 2
When running gating method with method 2 (average prior segment), the returned signal might contain nan values. The presence of such values blocks the application of further processing (e.g., filtering). 

An example of this behaviour has been experienced using the M004/003 dataset in the dashboard, as reported [here](#142).

The method should be reviewed to deal with nan values and either substitute them (e.g., zero padding, average of previous samples) or to raise an exception.

### PR DESCRIPTION
**Pull request by rspwarnaar**
Fix ReSurfEMG/ReSurfEMG#143 ReSurfEMG/ReSurfEMG-dashboard#17
np.nanmean excludes nan values from the averaging window. 

If the windows exists of nan values only, it will still return a nan (both in method 2 and 3). I left this in as you probably want it to raise an error if you have your entire probing windows of nans: @fs=2048Hz, this would mean ~200 consecutive samples are nans, which probably mean your signal seriously corrupted.

### CODE REVIEW

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
I don't think this will handle the condition where this is no prior segment.

**Comment by rspwarnaar** [comment]
@drcandacemakedamoore Added the requested fix for no prior segment. 

NB for future reference: For method 3, this is not a problem, as it takes the non-nan average over the a window before and after the peak.

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
OK, now you just need to update your documentation to reflect this minor detail, and add a test to testing, and it should be good to go.

**Comment by drcandacemakedamoore** [comment]
Looking good! Now either you or @ElineOppersma just need to make sure this is rebased on the main so it picks up all the new stuff.

**Pull request merged**
