### PR TITLE
fast update instructions

### PR DESCRIPTION
**Pull request by drcandacemakedamoore**
please  see if you can get a mamba upgrade to work with python 3.9 and dependecies

### CODE REVIEW

**Comment by ghost** [comment]
This installs fine on Linux. Can you please check this on Windows? @drcandacemakedamoore

**Comment by drcandacemakedamoore** [comment]
This kind of install works. The mne package is used by the Poly5 reader (and nothing else). @wbaccinelli can you please run and compare files read in on both versions? If they are the same, we will upgrade to having a fast install with mamba and Python 3.9 everywhere.

**Comment by drcandacemakedamoore** [comment]
@wbaccinelli the check, which I can do part of involves 1. comparing version 0.21.2 of mne and 0.23.4 (https://zenodo.org/record/4298746) to see if the one function and one class we used (mne.create_info and mne.io.RawArray) changed between those versions in any meaningful way. Then 2. we need to run and compare a few samples and make sure there are no surprises. Maximal we can just rewrite tmsisdk_lite to have similar functions to the 21.2 version  inside of it, but probably we don't have to.

**Comment by drcandacemakedamoore** [comment]
@wbaccinelli I checked the archived versions of the different versions and mne.io.RawArray only changed in one line in the documentation, not the function. mne.create_info changed slightly.  There is a difference in mne.create_info(), but it should not make a difference. PLease test

**Review by wbaccinelli — APPROVED** [review]
Great! Tested on Windows and it works

**Comment by drcandacemakedamoore** [comment]
OK, some testing on array reading done.

**Pull request merged**
