### PR TITLE
Wbaccinelli/joss synth data

### PR DESCRIPTION
**Pull request by wbaccinelli**
Recovered the getting_stared notebook

### CODE REVIEW

**Review by drcandacemakedamoore — APPROVED** [review]
Great, but somehow you diverged from main. It is the cli module. I found the conflicts

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
Please let me know which version of cli you want. This is where you diverged from main., I can repair to either, then I will put this on the main

**Comment by wbaccinelli** [comment]
@drcandacemakedamoore Can you point me to the conflicts? I changed just the notebook and GitHub is not telling me anything

**Comment by drcandacemakedamoore** [comment]
If you try and rebase your branch on the main from command-line, then VS code should show you the conflicts. They are all in the cli module. Somehow one of us deleted the changes you made to the cli module. We should look at this carefully, and maybe retest it.

**Comment by wbaccinelli** [comment]
@drcandacemakedamoore even if the branch is wbaccinelli/joss-synth-data, the pull request is just about the getting_started notebook (see the files changed). Rebase and merge will only apply the two latest two commits. Indeed, locally rebasing commit by commit will raise conflicts, as the previous changes have been already been applied in the main.

**Review by drcandacemakedamoore — APPROVED** [review]

**Comment by drcandacemakedamoore** [comment]
Closed in favor of PR #259

**Pull request closed without merging**
