### PR TITLE
correct path for venv activation

### PR DESCRIPTION
**Pull request by wbaccinelli**
After checking, I confirm that the correct path is `.venv/Scripts/activate`

### CODE REVIEW

**Review by drcandacemakedamoore — CHANGES_REQUESTED** [review]
This is probably true if you use a pure Windows machine. I assumed 'true' developers are Linux users in most cases. Does the Scripts work on your WSL or Linux machine? On my mixed machine bin worked a while ago  I think we should put in separate instructions for Windows developers and Linux developers...

**Comment by drcandacemakedamoore** [comment]
@wvxvw can you please take a short look at this?

**Comment by ghost** [comment]
Hi, @wbaccinelli , I think, there's a typo here:

```diff
1 file changed, 2 insertions(+), 2 deletions(-)
README.md | 4 ++--

modified   README.md
@@ -194,9 +194,9 @@ Windows, we reccomend using `conda`.
 
    ```sh
    python3.8 -m venv .venv
-   . .venv/bin/activate
+   . .venv/Scripts/activate
    # Windows user need to run:
-   # .venv/bin/activate
+   # .venv/Scripts/activate
    python setup.py install_dev
    ```
```

I think, what you meant is:

```diff
1 file changed, 2 insertions(+), 2 deletions(-)
README.md | 4 ++--

modified   README.md
@@ -194,9 +194,9 @@ Windows, we reccomend using `conda`.
 
    ```sh
    python3.8 -m venv .venv
    . .venv/bin/activate
    # Windows user need to run:
-   # .venv/bin/activate
+   # .venv/Scripts/activate
    python setup.py install_dev
    ```
```

I.e. the comment `Windows user needs to run:` applies only to the code below it. Am I wrong? Or, if we want to put Windows users first, then keep the first change, but change the comment to say `Unix users need to run:`?

Technically, this isn't about the operating system, but the kind of Python they installed and how they ran it. I.e. you can install Python on Windows through MSYS2 (Cygwin) or, maybe even if you run Python from Unix shell (eg. Bash), while still on Windows it will create the virtual environment with `bin` directory rather than `Scripts`.

Now, that I think about it, I don't actually know what exactly this depends on. I'll have to investigate...

**Comment by ghost** [comment]
OK, here are my investigation results:

1. `venv` simply looks at `sys.executable` (at the time you called `venv`) and extracts the directory name from there. So, if you happened to install Python into `/foo/bar/python`, then `venv` will call that directory `bar`.
2. Python's own code seems to strongly believe that this value corresponds to `os.name`. If that value is `'nt'`, then Python's own code will assume that Python was installed into `Scripts` directory. However, in some other places, it believes that anything that is not `os.name == 'posix'` should produce the same result.  Obviously, on the other end, `os.name` is configurable... and the "third" option is possible when the system neither identifies as POSIX, nor as NT...

So... the ultimate test? -- Users should just look into the virtual environment they created and locate Python executable. I cannot think about a simple and portable way to do it programmatically though. But, maybe we can avoid it altogether by saying "users should activate the virtual environment they created"? Is it a stretch to think that users will figure out how to do it?

**Comment by drcandacemakedamoore** [comment]
On my machine now, something changed and it can't find my Python with these instructions alone, even when modified to Python3 instead of Python3.8. I think we should avoid all this complexity and just replace the entire section with a note that we are currently switching to a fully Python3.9 project, and in the future specific instructions for the install_dev may be added for advanced user. At present users can develop by using the type of installation in option A or option B. There isn't any kind of development I care about you need the install_dev option for as you can test and PR from the option A and B environment. Is anyone aware of someone running a fork who will have their own releases in the future, and if so can't someone so advanced just figure this out on their own? I don't think we need to be responsible for such people...thoughts?

**Comment by wbaccinelli** [comment]
> On my machine now, something changed and it can't find my Python with these instructions alone, even when modified to Python3 instead of Python3.8. I think we should avoid all this complexity and just replace the entire section with a note that we are currently switching to a fully Python3.9 project, and in the future specific instructions for the install_dev may be added for advanced user. At present users can develop by using the type of installation in option A or option B. There isn't any kind of development I care about you need the install_dev option for as you can test and PR from the option A and B environment. Is anyone aware of someone running a fork who will have their own releases in the future, and if so can't someone so advanced just figure this out on their own? I don't think we need to be responsible for such people...thoughts?

I agree with this. Let's just go for a reduction of the complexity

**Review by drcandacemakedamoore — APPROVED** [review]
I now changed it to a simplified version where we don't get into this. If you approve @wbaccinelli, please put it on themain

**Comment by drcandacemakedamoore** [comment]
@wbaccinelli I think it is ready to go now (I caught a lack of most correct version push)

**Pull request merged**
